/*
 * WordMaster.java
 *
 * Created on March 16, 2007, 6:17 PM
 */

package driver;

import java.util.ArrayList;

/**
 *
 * @author  Madhu
 */
public class WordMaster extends javax.swing.JFrame
{
    
    /**
     * Creates new form WordMaster
     */
    public WordMaster ()
    {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        cmdwordfind = new javax.swing.JButton();
        cmdasolver = new javax.swing.JButton();
        cmdcbuddy = new javax.swing.JButton();
        lblanagrams = new javax.swing.JLabel();
        lblword = new javax.swing.JLabel();
        cboanagrams = new javax.swing.JComboBox();
        txtword = new javax.swing.JTextField();
        check1 = new javax.swing.JCheckBox();
        lbltitle = new javax.swing.JLabel();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        check5 = new javax.swing.JCheckBox();
        check6 = new javax.swing.JCheckBox();
        check7 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cmdsearch = new javax.swing.JButton();
        lblresults = new javax.swing.JLabel();
        lblresdes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        cmdwordfind.setFont(new java.awt.Font("Tahoma", 1, 11));
        cmdwordfind.setText("Word Finder");
        cmdwordfind.setToolTipText("Find all possible words from within the given word");
        cmdwordfind.setPreferredSize(new java.awt.Dimension(123, 23));
        cmdwordfind.setRequestFocusEnabled(false);
        cmdwordfind.setRolloverEnabled(false);
        cmdwordfind.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cmdwordfindMouseClicked(evt);
            }
        });

        cmdasolver.setFont(new java.awt.Font("Tahoma", 1, 11));
        cmdasolver.setText("Anagram Solver");
        cmdasolver.setToolTipText("Find all possible anagrams of the given word");
        cmdasolver.setRequestFocusEnabled(false);
        cmdasolver.setRolloverEnabled(false);
        cmdasolver.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cmdasolverMouseClicked(evt);
            }
        });

        cmdcbuddy.setFont(new java.awt.Font("Tahoma", 1, 11));
        cmdcbuddy.setText("Crossword Buddy");
        cmdcbuddy.setToolTipText("Enter part of the word with '?' at the unknown locations");
        cmdcbuddy.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cmdcbuddyMouseClicked(evt);
            }
        });

        lblanagrams.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblanagrams.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblanagrams.setText("ANAGRAMS");

        lblword.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblword.setText("WORD");

        txtword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtwordKeyPressed(evt);
            }
        });

        check1.setFont(new java.awt.Font("Tahoma", 1, 11));
        check1.setText("2");
        check1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check1.setEnabled(false);
        check1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check1.setRequestFocusEnabled(false);
        check1.setRolloverEnabled(false);

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbltitle.setForeground(new java.awt.Color(0, 51, 51));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("ANAGRAM SOLVER");

        check2.setFont(new java.awt.Font("Tahoma", 1, 11));
        check2.setText("3");
        check2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check2.setEnabled(false);
        check2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check2.setRequestFocusEnabled(false);
        check2.setRolloverEnabled(false);

        check3.setFont(new java.awt.Font("Tahoma", 1, 11));
        check3.setText("4");
        check3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check3.setEnabled(false);
        check3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check3.setRequestFocusEnabled(false);
        check3.setRolloverEnabled(false);

        check4.setFont(new java.awt.Font("Tahoma", 1, 11));
        check4.setText("5");
        check4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check4.setEnabled(false);
        check4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check4.setRequestFocusEnabled(false);
        check4.setRolloverEnabled(false);

        check5.setFont(new java.awt.Font("Tahoma", 1, 11));
        check5.setText("6");
        check5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check5.setEnabled(false);
        check5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check5.setRequestFocusEnabled(false);
        check5.setRolloverEnabled(false);

        check6.setFont(new java.awt.Font("Tahoma", 1, 11));
        check6.setText("7");
        check6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check6.setEnabled(false);
        check6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check6.setRequestFocusEnabled(false);
        check6.setRolloverEnabled(false);

        check7.setFont(new java.awt.Font("Tahoma", 1, 11));
        check7.setText(">7");
        check7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        check7.setEnabled(false);
        check7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        check7.setRequestFocusEnabled(false);
        check7.setRolloverEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WORD MASTER v2.0");

        cmdsearch.setFont(new java.awt.Font("Tahoma", 1, 11));
        cmdsearch.setText("SEARCH");
        cmdsearch.setToolTipText("Go");
        cmdsearch.setRequestFocusEnabled(false);
        cmdsearch.setRolloverEnabled(false);
        cmdsearch.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cmdsearchMouseClicked(evt);
            }
        });

        lblresults.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblresdes.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblresdes.setText("results found");
        lblresdes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmdwordfind, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdasolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(cmdcbuddy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblanagrams)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(check1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(check2))
                                    .addComponent(lblword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmdsearch)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblresults, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(lblresdes)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(check3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(check4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(check5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(check6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(check7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboanagrams, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtword, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))))
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdasolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdwordfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdcbuddy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(check7)
                        .addComponent(check6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(check5)
                        .addComponent(check4)
                        .addComponent(check3)
                        .addComponent(check2)
                        .addComponent(check1)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblword))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblanagrams)
                    .addComponent(cboanagrams, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(cmdsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblresdes)
                    .addComponent(lblresults, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsearchMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_cmdsearchMouseClicked
    {//GEN-HEADEREND:event_cmdsearchMouseClicked
        if(appType==1)
        {
            cboanagrams.removeAllItems ();
            Nanagram one = new Nanagram ();
            Starter st = new Starter ();
            StringBuffer name1 = new StringBuffer (txtword.getText ().toLowerCase ());
            Structure pass = new Structure ();
            try
            {
                pass=st.createStructure (name1.toString ());
            }
            catch(Exception err)
            {
                System.out.println (err);
            }
            
            try
            {
                one.find (cboanagrams,pass,aList,name1.length ());
            }
            catch(Exception err)
            {
                System.out.println (err);
            }
            lblresults.setText (Integer.toString (one.count));
        }
        else if(appType==2)
        {
            cboanagrams.removeAllItems ();
            Starter st = new Starter ();
            WordFinder two = new WordFinder ();
            StringBuffer name1 = new StringBuffer (txtword.getText ().toLowerCase ());
            Structure pass = new Structure ();
            int[] len = new int[7];
            for(int i=0;i<7;i++)
                len[i]=0;
            if(check1.isSelected ())
                len[0]=1;
            if(check2.isSelected ())
                len[1]=1;
            if(check3.isSelected ())
                len[2]=1;
            if(check4.isSelected ())
                len[3]=1;
            if(check5.isSelected ())
                len[4]=1;
            if(check6.isSelected ())
                len[5]=1;
            if(check7.isSelected ())
                len[6]=1;
            
            try
            {
                pass=st.createStructure (name1.toString ());
            }
            catch(Exception err)
            {
                System.out.println (err);
            }
            try
            {
                two.finder (pass,aList,cboanagrams,len);
            }
            catch(Exception err)
            {
                System.out.println (err);
            }
            lblresults.setText (Integer.toString (two.count));
        }
        else if(appType==3)
        {
            cboanagrams.removeAllItems ();
            CrosswordBuddy cb = new CrosswordBuddy ();
            cb.crossSolve (txtword.getText ().toLowerCase (),aList,cboanagrams);
            lblresults.setText (Integer.toString (cb.count));
        }
    }//GEN-LAST:event_cmdsearchMouseClicked

    private void txtwordKeyPressed (java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtwordKeyPressed
    {//GEN-HEADEREND:event_txtwordKeyPressed
        if(evt.getKeyCode ()==10)
        {
            if(appType==1)
            {
                cboanagrams.removeAllItems ();
                Nanagram one = new Nanagram ();
                Starter st = new Starter ();
                StringBuffer name1 = new StringBuffer (txtword.getText ().toLowerCase ());
                Structure pass = new Structure ();
                try
                {
                    pass=st.createStructure (name1.toString ());
                }
                catch(Exception err)
                {
                    System.out.println (err);
                }
                
                try
                {
                    one.find (cboanagrams,pass,aList,name1.length ());
                }
                catch(Exception err)
                {
                    System.out.println (err);
                }
                lblresults.setText (Integer.toString (one.count));
            }
            else if(appType==2)
            {
                cboanagrams.removeAllItems ();
                Starter st = new Starter ();
                WordFinder two = new WordFinder ();
                StringBuffer name1 = new StringBuffer (txtword.getText ().toLowerCase ());
                Structure pass = new Structure ();
                int[] len = new int[7];
                for(int i=0;i<7;i++)
                    len[i]=0;
                if(check1.isSelected ())
                    len[0]=1;
                if(check2.isSelected ())
                    len[1]=1;
                if(check3.isSelected ())
                    len[2]=1;
                if(check4.isSelected ())
                    len[3]=1;
                if(check5.isSelected ())
                    len[4]=1;
                if(check6.isSelected ())
                    len[5]=1;
                if(check7.isSelected ())
                    len[6]=1;
                try
                {
                    pass=st.createStructure (name1.toString ());
                }
                catch(Exception err)
                {
                    System.out.println (err);
                }
                try
                {
                    two.finder (pass,aList,cboanagrams,len);
                }
                catch(Exception err)
                {
                    System.out.println (err);
                }
                lblresults.setText (Integer.toString (two.count));
            }
            else if(appType==3)
            {
                cboanagrams.removeAllItems ();
                CrosswordBuddy cb = new CrosswordBuddy ();
                cb.crossSolve (txtword.getText ().toLowerCase (),aList,cboanagrams);
                lblresults.setText (Integer.toString (cb.count));
            }
            
        }
    }//GEN-LAST:event_txtwordKeyPressed

    private void cmdcbuddyMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_cmdcbuddyMouseClicked
    {//GEN-HEADEREND:event_cmdcbuddyMouseClicked
        appType=3;
        cboanagrams.removeAllItems ();
        lblresults.setText ("");
        txtword.setText ("");
        lbltitle.setText ("CROSSWORD BUDDY");
        lblanagrams.setText ("WORD LIST");
        check1.setEnabled (false);
        check2.setEnabled (false);
        check3.setEnabled (false);
        check4.setEnabled (false);
        check5.setEnabled (false);
        check6.setEnabled (false);
        check7.setEnabled (false);
    }//GEN-LAST:event_cmdcbuddyMouseClicked

    private void cmdasolverMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_cmdasolverMouseClicked
    {//GEN-HEADEREND:event_cmdasolverMouseClicked
        appType=1;
        cboanagrams.removeAllItems ();
        lblresults.setText ("");
        txtword.setText ("");
        lbltitle.setText ("ANAGRAM SOLVER");
        lblanagrams.setText ("ANAGRAMS");
        check1.setEnabled (false);
        check2.setEnabled (false);
        check3.setEnabled (false);
        check4.setEnabled (false);
        check5.setEnabled (false);
        check6.setEnabled (false);
        check7.setEnabled (false);
    }//GEN-LAST:event_cmdasolverMouseClicked

    private void cmdwordfindMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_cmdwordfindMouseClicked
    {//GEN-HEADEREND:event_cmdwordfindMouseClicked
        appType=2;
        cboanagrams.removeAllItems ();
        lblresults.setText ("");
        txtword.setText ("");
        lbltitle.setText ("WORD FINDER");
        lblanagrams.setText ("WORD LIST");
        check1.setEnabled (true);
        check2.setEnabled (true);
        check3.setEnabled (true);
        check4.setEnabled (true);
        check5.setEnabled (true);
        check6.setEnabled (true);
        check7.setEnabled (true);
        check1.setSelected (false);
        check2.setSelected (false);
        check3.setSelected (false);
        check4.setSelected (false);
        check5.setSelected (false);
        check6.setSelected (false);
        check7.setSelected (false);
    }//GEN-LAST:event_cmdwordfindMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        java.awt.EventQueue.invokeLater (new Runnable ()
        {
            public void run ()
            {
                new WordMaster ().setVisible (true);
            }
        });
    }
    ArrayList[][] aList = new ArrayList[26][15];
    int appType;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboanagrams;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JCheckBox check6;
    private javax.swing.JCheckBox check7;
    private javax.swing.JButton cmdasolver;
    private javax.swing.JButton cmdcbuddy;
    private javax.swing.JButton cmdsearch;
    private javax.swing.JButton cmdwordfind;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblanagrams;
    private javax.swing.JLabel lblresdes;
    private javax.swing.JLabel lblresults;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblword;
    private javax.swing.JTextField txtword;
    // End of variables declaration//GEN-END:variables
    
}
